name: Bump bwc version

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*.*'

permissions: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub App token
        id: github_app_token
        uses: tibdex/github-app-token@v1.5.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          #installation_id: 22958780
          installation_id: 42934585

      - uses: actions/checkout@v4
      - name: Fetch Tag and Version Information
        run: |
          TAG=$(echo "${GITHUB_REF#refs/*/}")
          CURRENT_VERSION_ARRAY=($(echo "$TAG" | tr . '\n'))
          CURRENT_VERSION=$(IFS=. ; echo "${CURRENT_VERSION_ARRAY[*]:0:3}")
          CURRENT_VERSION_ARRAY[1]=$((CURRENT_VERSION_ARRAY[1]+1))
          NEXT_VERSION=$(IFS=. ; echo "${CURRENT_VERSION_ARRAY[*]:0:3}")
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ steps.github_app_token.outputs.token }}

      - name: Add bwc version to main branch
        run: |
          echo Adding bwc version $NEXT_VERSION after $CURRENT_VERSION
          sed -i "s/def bwcVersionShort = \"$CURRENT_VERSION\"/def bwcVersionShort = \"$NEXT_VERSION\"/g" notifications/notifications/build.gradle

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.github_app_token.outputs.token }}
          base: main
          branch: 'create-pull-request/patch-main'
          commit-message: Add bwc version ${{ env.NEXT_VERSION }}
          signoff: true
          delete-branch: true
          labels: |
            autocut
          title: '[AUTO] [main] Bump bwc version to ${{ env.NEXT_VERSION }}.'
          body: |
            I've noticed that a new tag ${{ env.TAG }} was pushed, and bump bwc version to ${{ env.NEXT_VERSION }}.

